### ISSUE TITLE
After Fresh installation showing The request has been black-holed Error: The requested address '/wzusers/login' was not found on this server.

### ISSUE THREAD

**Issue by yayas87** [prashants/webzash#38] opened 2015-11-21 17:31 UTC
Webzash
Errors
The request has been black-holed
Error: The requested address '/wzusers/login' was not found on this server.

Stack Trace
CORE/Cake/Controller/Component/SecurityComponent.php line 239 → SecurityComponent->blackHole(WzusersController, string)
[internal function] → SecurityComponent->startup(WzusersController)
CORE/Cake/Utility/ObjectCollection.php line 128 → call_user_func_array(array, array)
[internal function] → ObjectCollection->trigger(CakeEvent)
CORE/Cake/Event/CakeEventManager.php line 242 → call_user_func(array, CakeEvent)
CORE/Cake/Controller/Controller.php line 675 → CakeEventManager->dispatch(CakeEvent)
CORE/Cake/Routing/Dispatcher.php line 187 → Controller->startupProcess()
CORE/Cake/Routing/Dispatcher.php line 165 → Dispatcher->_invoke(WzusersController, CakeRequest)
APP/webroot/index.php line 108 → Dispatcher->dispatch(CakeRequest, CakeResponse)
Powered by Webzash v2.6

**Comment by prashants** [comment] 2015-11-21 17:53
It is a security feature. The page has timed out. Just reload the page.

**Comment by prashants** [comment] 2015-11-27 05:55
Closing it issue. If its not resolved please reopen it.

**Comment by yayas87** [comment] 2015-11-27 06:18
It has not yet resolved, how can i clear this issue.

thanks

**Comment by chacha** [comment] 2015-11-27 06:20
It does seem like very poor user experience. It would be nice to either disable or increase the threshold.

At least, making it not a super scary terrible error message might be in order.

**Comment by yayas87** [comment] 2015-11-27 06:32
I am using cPanel, Can u guide me how to adjust the threshold

thanks

**Comment by prashants** [comment] 2015-11-27 06:48
@chacha - will fix it in next release

@yayas87 - when did you get this error ? where you able to login and create the account ?

**Comment by yayas87** [comment] 2015-11-27 06:50
These were the steps which did,
1. extracted the files to folder
2. open the url
3. logged in as admin, admin
4. After that, the error page displayed.

**Comment by prashants** [comment] 2015-11-27 18:27
Try using http instead of https

Another option is to temporarily disable security component in cakephp

**Comment by prashants** [comment] 2015-11-28 17:08
Did changing from http from https fix the issue ? Maybe there is some issue with the server configuration, since lot of users are using it without any problems.

Can you email me where you are trying to host. I will have to personally look at it.

**Comment by yayas87** [comment] 2015-11-29 09:14
The issue has not yet solved.

http://webzash.zaliyo.in

please check here

**Comment by yayas87** [comment] 2015-11-29 09:17
I have send you a mail to pshah.mumbai@gmail.com

please check

**Comment by prashants** [comment] 2015-11-29 13:08
I have disable the security component and its working. Its a temporary solution.

In the file /home/webzash/public_html/app/Plugin/Webzash/Controller/WebzashAppController.php

	public $components = array(
		'Security', 'Session', 'Paginator', 'Webzash.Permission', 'Webzash.Generic',
		'Webzash.CustomPaginator',
		'Auth' => array(

I have removed the word 'Security'

There is some issue with the server. The PHP settings are not correct because of which its not working.

**Comment by yayas87** [comment] 2015-11-29 14:21
Thanks for the fix bro,

I am using the PHP Version 5.6.15 and Apache 2.4.16 

that issue has been solved now. Another issue I noticed is when i visited domain.com/entries/index

its displaying some error

![image](https://cloud.githubusercontent.com/assets/1930172/11457575/8793cfc4-96d2-11e5-873b-0f389d7f8b8f.png)

**Comment by yayas87** [comment] 2015-11-29 14:25
So, I opened /home/webzash/public_html/app/Plugin/Webzash/Controller/EntriesController.php

commented line number 1156 and 1158. 

is there any issues for this action?

thanks

**Comment by prashants** [comment] 2015-11-29 14:34
Yeah you need to comment out $this->Security->unlockedActions and $this->Security->unlockedFields throughout the app. There are no issues with commenting it out.

Better is to check with bitnami lamp stack php config and your config and see where the issue is

**Closed** 2015-11-29 17:23 UTC
