### ISSUE TITLE
Failed to send email

### ISSUE THREAD

**Issue by sibidharan** [prashants/webzash#77] opened 2016-09-17 12:42 UTC
SMTP settings are perfect, I am using the same smtp in many other services on same server. Still, failed to send email.

**Comment by prashants** [comment] 2016-09-17 16:58
http://book.cakephp.org/2.0/en/core-utility-libraries/email.html

Since its using cakephp to send emails, the issue is most probably with cakephp.

Can you make a small cakphp page to send email and see what's wrong.

**Comment by sibidharan** [comment] 2016-09-18 04:00
Sure, let me try!

**Comment by prashants** [comment] 2017-05-05 07:55
If the problem persists please reopen this issue. Closing it for now.

**Closed by prashants** 2017-05-05 07:55 UTC
